INSERT INTO organization_type (name) VALUES
	('ACCOUNTING_PRACTICE'),
	('CHARITY'),
	('CLUB_OR_SOCIETY'),
	('COMPANY'),
	('INDIVIDUAL'),
	('LOOK_THROUGH_COMPANY'),
	('NOT_FOR_PROFIT'),
	('PARTNERSHIP'),
	('S_CORPORATION'),
	('SELF_MANAGED_SUPERANNUATION_FUND'),
	('SOLE_TRADER'),
	('SUPERANNUATION_FUND'),
	('TRUST');