spring:
   application:
      name: "backend"
   docker: # Docker configuration 
      compose:
         enabled: true
         file: "compose.yaml"
   # Flyway configuration      
   flyway:
      enabled: true
      encoding: UTF-8
      connect-retries: 5
      create-schemas: true
      schemas: "app_sc"
      default-schema: "app_sc"
      url: ${DB_URL}
      user: ${DB_USER}
      password: ${DB_PASSWORD}
      execute-in-transaction: true
      locations: classpath:db/migration
      clean-disabled: false
   # Configure datasource
   datasource:
      driver-class-name: org.postgresql.Driver
      username: ${DB_USER}
      password: ${DB_PASSWORD}
   # Configure Hibernate
   jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect 
      properties:
         hibernate:
            generate_statistics: true # ONLY FOR DEVELOPMENT
      hibernate:
         ddl-auto: none
      show-sql: true
   # Configure for JWT auth
   app:
      jwt:
         secret: ${JWT_SECRET}
         access-token: 480000
         refresh-token: 1.44e+6
      details:
         api:
            website: "https://restcountries.com/v3.1"
         default_credentials:
            default_first_name: "Brian"
            default_last_name: "Tmblr"
            default_email: "defaultEmail1999@sample.com"
            default_password: "password123"
server:
   port: 8900